### ISSUE TITLE
string conversion error

### ISSUE THREAD

**Issue by asraghu123** [jeffreyrdcs/stock-vcp-dash#3]
Hi,  I have installed all the requirements.txt packages and their versions.   
![image](https://github.com/jeffreyrdcs/stock-vcp-dash/assets/76263329/52250bee-9a7b-4901-a8e0-6be96085b015)

I get this error.   I have also replaced _STOCK_INFO_URL_PATH_NAME = 'C:/Users/asraghu/VCP/stock_vcpscreener/'  where the file daily_selected_stock_info.csv exists as per your directions.

I have uploaded the daily_selected_stock_info.csv to a gdrive as the size is 37mb and the limit to attach is only 25MB.  here is the link

https://drive.google.com/file/d/1Lh_TVORVr5ZGtfRnfjGKTI2pG__fgqnJ/view?usp=drive_link

**Comment by wilsonlam1** [comment]
@asraghu123 @jeffreyrdcs 

I ran the code as below error:
![image](https://github.com/jeffreyrdcs/stock-vcp-dash/assets/163280221/b10aeb6e-1ed4-4662-a401-6d73eaa11800)

Would you please help to have a look, thanks!
[my installation.txt](https://github.com/jeffreyrdcs/stock-vcp-dash/files/14716686/my.installation.txt)

**Comment by asraghu123** [comment]
looks both of us have the same issue.   We need @jeffreyrdcs  to handhold us to cross over the bridge across the python river.

**Comment by asraghu123** [comment]
@jeffreyrdcs @wilsonlam1 

In line 94 of the app.py,  I added these lines to circumvent the error.  The output comes correctly.   maybe there is a better implementation that you can suggest.  

def _convert_str_list_column_to_float(in_str):
    """Convert the string column back into an array of float. Could use np.fromstring(mmmm.strip("[]"), sep=',')."""
    in_str = re.sub("[\[\]']", '', in_str)
    if in_str == '':
      return in_str
    else:
      return np.array(in_str.split(',')).astype(float)


![image](https://github.com/jeffreyrdcs/stock-vcp-dash/assets/76263329/b60e3eb7-6c6e-4d74-bd40-413420695f36)

![image](https://github.com/jeffreyrdcs/stock-vcp-dash/assets/76263329/d1412553-cfcb-4c8b-9efa-a3869bb7f67b)

**Comment by asraghu123** [comment]
Thanks and closing the issue
